import React from 'react';

export interface ConfirmationSection {
  id: string;
  title: string;
  customerVisible: boolean;
  content: React.ReactNode;
}

export interface ReservationConfirmationData {
  profileType: string;
  callType: string;
  companyName: string;
  dealName?: string;
  setupName?: string;
  setupEmail?: string;
  callDate?: string;
  startTime?: string;
  timeZone?: string;
  host?: string;
  duration?: string;
  hostPasscode?: string;
  guestPasscode?: string;
  conferenceId?: string;
  reservationId?: string;
  dialInNumbers?: string;
  internationalDialInNumbers?: string;
  speakerDialInNumbers?: string;
  speakerInternationalDialInNumbers?: string;
  participantDialInNumbers?: string;
  participantInternationalDialInNumbers?: string;
  speakerDirectAccessLink?: string;
  participantDirectAccessLink?: string;
  multiview?: string;
  multiviewAccessLink?: string;
  conferenceReplay?: string;
  replayAccessLink?: string;
  participants?: string;
  bridgeInstructions?: string;
  notes?: string;
  referenceName?: string;
  // Assisted specific fields
  speakerConferenceId?: string;
  participantConferenceId?: string;
  listenOnlyDirectAccessLink?: string;
  listenOnlyDialInNumbers?: string;
  listenOnlyInternationalDialInNumbers?: string;
  listenOnlyConferenceId?: string;
  replayFromDate?: string;
  replayToDate?: string;
  replayEndTime?: string;
  replayTimeZone?: string;
  replayCode?: string;
  multiviewUsername?: string;
  multiviewConferenceNumber?: string;
  participantList?: string;
  participantListInformation?: string;
  participantListRecipientEmail?: string;
  operatorScript?: string;
  operatorScriptVerbiage?: string;
  conferenceMP3?: string;
  conferenceTranscript?: string;
  turnaroundTime?: string;
  qa?: string;
  qaSpecificOrder?: string;
  listenOnlyBridgeName?: string;
  replayParticipantListRecipientEmail?: string;
  other?: string;
}

interface ConfirmationRendererProps {
  data: ReservationConfirmationData;
  mode: 'page' | 'email';
  className?: string;
}

export const ConfirmationRenderer: React.FC<ConfirmationRendererProps> = ({ 
  data, 
  mode, 
  className = '' 
}) => {
  const sections = generateSections(data);

  if (mode === 'email') {
    return <EmailRenderer sections={sections} data={data} />;
  }

  return <PageRenderer sections={sections} className={className} />;
};

const PageRenderer: React.FC<{ sections: ConfirmationSection[], className: string }> = ({ 
  sections, 
  className 
}) => {
  return (
    <div className={`space-y-8 ${className}`}>
      {sections.map((section) => (
        <div key={section.id} className="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden">
          <div className="px-6 py-4 bg-gray-50 border-b border-gray-200">
            <h2 className="text-lg font-semibold text-gray-900">{section.title}</h2>
          </div>
          <div className="p-6">
            {section.content}
          </div>
        </div>
      ))}
    </div>
  );
};

const EmailRenderer: React.FC<{ sections: ConfirmationSection[], data: ReservationConfirmationData }> = ({ 
  sections, 
  data 
}) => {
  const customerVisibleSections = sections.filter(section => section.customerVisible);

  const emailHtml = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Reservation Confirmation</title>
    </head>
    <body style="margin: 0; padding: 0; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; background-color: #f4f4f4;">
      <div style="max-width: 700px; margin: 20px auto; background: white; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); overflow: hidden;">
        
        <!-- Header -->
        <div style="background: linear-gradient(135deg, #1f2a44 0%, #2c3e50 100%); color: white; padding: 30px 20px; text-align: center;">
          <h1 style="margin: 0; font-size: 28px; font-weight: 300;">Reservation Confirmation</h1>
          <p style="margin: 10px 0 0 0; opacity: 0.9;">Your conference call has been scheduled</p>
        </div>

        <!-- Content -->
        <div style="padding: 30px;">
          ${customerVisibleSections.map(section => `
            <div style="margin-bottom: 30px;">
              <h2 style="color: #1f2a44; border-bottom: 2px solid #e1e8ed; padding-bottom: 10px; margin-bottom: 20px;">${section.title}</h2>
              ${renderSectionContentForEmail(section, data)}
            </div>
          `).join('')}
        </div>

        <!-- Footer -->
        <div style="background: #f8f9fa; padding: 20px; text-align: center; border-top: 1px solid #e1e8ed;">
          <p style="margin: 0; font-size: 12px; color: #666;">
            This message was generated by the Reservation Form system.<br>
            If you have any questions, please contact your conference coordinator.
          </p>
        </div>
        
      </div>
    </body>
    </html>
  `;

  return <div dangerouslySetInnerHTML={{ __html: emailHtml }} />;
};

const renderSectionContentForEmail = (section: ConfirmationSection, data: ReservationConfirmationData): string => {
  // This is a simplified version - in a real implementation, you'd need to convert
  // React components to HTML strings. For now, we'll use the existing formatEmail logic
  // as a starting point and enhance it.
  
  if (section.id === 'reservation-details') {
    return `
      <table cellpadding="12" cellspacing="0" style="border-collapse: collapse; width: 100%; font-size: 14px;">
        <tr>
          <td style="font-weight: 600; color: #555; width: 180px; vertical-align: top;">Profile Type</td>
          <td style="background: #f8f9fa; padding: 12px; border-radius: 4px;">${data.profileType}</td>
        </tr>
        <tr>
          <td style="font-weight: 600; color: #555; width: 180px; vertical-align: top;">Call Type</td>
          <td style="background: #f8f9fa; padding: 12px; border-radius: 4px;">${data.callType}</td>
        </tr>
        <tr>
          <td style="font-weight: 600; color: #555; width: 180px; vertical-align: top;">Company Name</td>
          <td style="background: #f8f9fa; padding: 12px; border-radius: 4px;">${data.companyName}</td>
        </tr>
        ${data.dealName ? `
        <tr>
          <td style="font-weight: 600; color: #555; width: 180px; vertical-align: top;">Deal / Reference Name</td>
          <td style="background: #f8f9fa; padding: 12px; border-radius: 4px;">${data.dealName}</td>
        </tr>` : ''}
        ${data.setupName ? `
        <tr>
          <td style="font-weight: 600; color: #555; width: 180px; vertical-align: top;">Setup Contact</td>
          <td style="background: #f8f9fa; padding: 12px; border-radius: 4px;">${data.setupName}</td>
        </tr>` : ''}
        ${data.setupEmail ? `
        <tr>
          <td style="font-weight: 600; color: #555; width: 180px; vertical-align: top;">Setup Email</td>
          <td style="background: #f8f9fa; padding: 12px; border-radius: 4px;">${data.setupEmail}</td>
        </tr>` : ''}
      </table>
    `;
  }

  // Add more section renderers as needed
  return '<div>Section content</div>';
};

const generateSections = (data: ReservationConfirmationData): ConfirmationSection[] => {
  const sections: ConfirmationSection[] = [];

  // Reservation Details Section (Customer Visible)
  sections.push({
    id: 'reservation-details',
    title: 'Reservation Details',
    customerVisible: true,
    content: <ReservationDetailsSection data={data} />
  });

  // Schedule Section (Customer Visible)
  if (data.callDate || data.startTime || data.timeZone) {
    sections.push({
      id: 'schedule',
      title: 'Call Schedule',
      customerVisible: true,
      content: <ScheduleSection data={data} />
    });
  }

  // Access Information Section (Customer Visible)
  if (hasAccessInfo(data)) {
    sections.push({
      id: 'access-information',
      title: 'Access / Dial-In Information',
      customerVisible: true,
      content: <AccessInformationSection data={data} />
    });
  }

  // Access Links Section (Customer Visible)
  if (hasAccessLinks(data)) {
    sections.push({
      id: 'access-links',
      title: 'Access Links',
      customerVisible: true,
      content: <AccessLinksSection data={data} />
    });
  }

  // Replay Information Section (Customer Visible)
  if (data.conferenceReplay === 'Yes' || data.multiview === 'Yes') {
    sections.push({
      id: 'replay-information',
      title: 'Replay Information',
      customerVisible: true,
      content: <ReplayInformationSection data={data} />
    });
  }

  // Important Notices Section (Customer Visible)
  if (hasImportantNotices(data)) {
    sections.push({
      id: 'important-notices',
      title: 'Important Notices / Instructions',
      customerVisible: true,
      content: <ImportantNoticesSection data={data} />
    });
  }

  // Coordinator Instructions Section (Internal Only)
  sections.push({
    id: 'coordinator-instructions',
    title: 'Coordinator Instructions',
    customerVisible: false,
    content: <CoordinatorInstructionsSection data={data} />
  });

  return sections;
};

// Helper Components for Each Section
const ReservationDetailsSection: React.FC<{ data: ReservationConfirmationData }> = ({ data }) => (
  <div className="space-y-4">
    <DetailRow label="Profile Type" value={data.profileType} />
    <DetailRow label="Call Type" value={data.callType} />
    <DetailRow label="Company Name" value={data.companyName} />
    {data.dealName && <DetailRow label="Deal / Reference Name" value={data.dealName} />}
    {data.setupName && <DetailRow label="Setup Contact" value={data.setupName} />}
    {data.setupEmail && <DetailRow label="Setup Email" value={data.setupEmail} />}
  </div>
);

const ScheduleSection: React.FC<{ data: ReservationConfirmationData }> = ({ data }) => (
  <div className="space-y-4">
    {data.callDate && <DetailRow label="Date" value={data.callDate} />}
    {data.startTime && (
      <DetailRow 
        label="Time" 
        value={`${data.startTime}${data.timeZone ? ` (${data.timeZone})` : ''}`} 
      />
    )}
    {data.duration && <DetailRow label="Duration" value={data.duration} />}
    {data.host && <DetailRow label="Host" value={data.host} />}
  </div>
);

const AccessInformationSection: React.FC<{ data: ReservationConfirmationData }> = ({ data }) => (
  <div className="space-y-4">
    {data.dialInNumbers && (
      <div>
        <h3 className="font-medium text-gray-900 mb-2">Dial-In Numbers</h3>
        <div className="bg-blue-50 border-l-4 border-blue-400 p-3 rounded user-select-all">
          <pre className="text-sm whitespace-pre-wrap">{data.dialInNumbers}</pre>
        </div>
      </div>
    )}
    
    {data.internationalDialInNumbers && (
      <div>
        <h3 className="font-medium text-gray-900 mb-2">International Dial-In Numbers</h3>
        <div className="bg-blue-50 border-l-4 border-blue-400 p-3 rounded user-select-all">
          <pre className="text-sm whitespace-pre-wrap">{data.internationalDialInNumbers}</pre>
        </div>
      </div>
    )}
    
    {data.speakerDialInNumbers && (
      <div>
        <h3 className="font-medium text-gray-900 mb-2">Speaker Dial-In Numbers</h3>
        <div className="bg-yellow-50 border-l-4 border-yellow-400 p-3 rounded user-select-all">
          <pre className="text-sm whitespace-pre-wrap">{data.speakerDialInNumbers}</pre>
        </div>
      </div>
    )}
    
    {data.participantDialInNumbers && (
      <div>
        <h3 className="font-medium text-gray-900 mb-2">Participant Dial-In Numbers</h3>
        <div className="bg-yellow-50 border-l-4 border-yellow-400 p-3 rounded user-select-all">
          <pre className="text-sm whitespace-pre-wrap">{data.participantDialInNumbers}</pre>
        </div>
      </div>
    )}
    
    <div className="space-y-3">
      {data.hostPasscode && (
        <SecureField label="Host Passcode" value={data.hostPasscode} />
      )}
      {data.guestPasscode && (
        <SecureField label="Guest Passcode" value={data.guestPasscode} />
      )}
      {data.conferenceId && (
        <SecureField label="Conference ID" value={data.conferenceId} />
      )}
      {data.reservationId && (
        <DetailRow label="Reservation ID" value={data.reservationId} />
      )}
    </div>
  </div>
);

const AccessLinksSection: React.FC<{ data: ReservationConfirmationData }> = ({ data }) => (
  <div className="space-y-4">
    {data.speakerDirectAccessLink && (
      <div>
        <h3 className="font-medium text-gray-900 mb-2">Speaker Direct Access Link</h3>
        <div className="bg-purple-50 border-l-4 border-purple-400 p-3 rounded">
          <a 
            href={data.speakerDirectAccessLink} 
            className="text-purple-700 hover:text-purple-900 underline break-all user-select-all"
            target="_blank"
            rel="noopener noreferrer"
          >
            {data.speakerDirectAccessLink}
          </a>
        </div>
      </div>
    )}
    
    {data.participantDirectAccessLink && (
      <div>
        <h3 className="font-medium text-gray-900 mb-2">Participant Direct Access Link</h3>
        <div className="bg-purple-50 border-l-4 border-purple-400 p-3 rounded">
          <a 
            href={data.participantDirectAccessLink} 
            className="text-purple-700 hover:text-purple-900 underline break-all user-select-all"
            target="_blank"
            rel="noopener noreferrer"
          >
            {data.participantDirectAccessLink}
          </a>
        </div>
      </div>
    )}
    
    {data.multiview === 'Yes' && data.multiviewAccessLink && (
      <div>
        <h3 className="font-medium text-gray-900 mb-2">Multiview Access Link</h3>
        <div className="bg-blue-50 border-l-4 border-blue-400 p-3 rounded">
          <a 
            href={data.multiviewAccessLink} 
            className="text-blue-700 hover:text-blue-900 underline break-all user-select-all"
            target="_blank"
            rel="noopener noreferrer"
          >
            {data.multiviewAccessLink}
          </a>
        </div>
      </div>
    )}
    
    {data.conferenceReplay === 'Yes' && data.replayAccessLink && (
      <div>
        <h3 className="font-medium text-gray-900 mb-2">Conference Replay Link</h3>
        <div className="bg-green-50 border-l-4 border-green-400 p-3 rounded">
          <a 
            href={data.replayAccessLink} 
            className="text-green-700 hover:text-green-900 underline break-all user-select-all"
            target="_blank"
            rel="noopener noreferrer"
          >
            {data.replayAccessLink}
          </a>
        </div>
      </div>
    )}
  </div>
);

const ReplayInformationSection: React.FC<{ data: ReservationConfirmationData }> = ({ data }) => (
  <div className="space-y-4">
    {data.conferenceReplay === 'Yes' && (
      <div>
        <h3 className="font-medium text-gray-900 mb-2">Conference Replay</h3>
        <div className="bg-gray-50 p-3 rounded space-y-2">
          {data.replayFromDate && <DetailRow label="From Date" value={data.replayFromDate} />}
          {data.replayToDate && <DetailRow label="To Date" value={data.replayToDate} />}
          {data.replayEndTime && <DetailRow label="End Time" value={data.replayEndTime} />}
          {data.replayTimeZone && <DetailRow label="Time Zone" value={data.replayTimeZone} />}
          {data.replayCode && <SecureField label="Replay Code" value={data.replayCode} />}
        </div>
      </div>
    )}
    
    {data.multiview === 'Yes' && (
      <div>
        <h3 className="font-medium text-gray-900 mb-2">Multiview Details</h3>
        <div className="bg-gray-50 p-3 rounded space-y-2">
          {data.multiviewUsername && <DetailRow label="Username" value={data.multiviewUsername} />}
          {data.multiviewConferenceNumber && <DetailRow label="Conference Number" value={data.multiviewConferenceNumber} />}
        </div>
      </div>
    )}
  </div>
);

const ImportantNoticesSection: React.FC<{ data: ReservationConfirmationData }> = ({ data }) => (
  <div className="space-y-4">
    {data.profileType === 'Assisted' && (
      <div className="bg-yellow-50 border border-yellow-200 p-4 rounded-md">
        <p className="text-sm text-yellow-800 font-medium mb-2">
          Please note that we have provided the following Direct Access links to your Invite:
        </p>
        <ul className="text-sm text-yellow-800 space-y-1 ml-4">
          <li>• Speaker Direct Access Link</li>
          <li>• Participant Direct Access Link</li>
        </ul>
        <p className="text-sm text-yellow-800 mt-2">
          It is imperative that the correct Direct Access link is provided to the correct intended party to avoid Participants joining the Speaker Sub Conference prior to call start time.
        </p>
      </div>
    )}
    
    {(data.profileType === 'Assisted' || data.profileType === 'Passcode') && (
      <div className="bg-red-50 border border-red-200 p-4 rounded-md">
        <p className="text-sm text-red-800 font-bold">
          Please provide the SPEAKER DIAL IN NUMBERS and SPEAKER Conference ID to the Technician if the call is taking place in an Auditorium and a Main Feed Line is needed to connect the call from the Auditorium to our Conferencing Bridge
        </p>
      </div>
    )}
  </div>
);

const CoordinatorInstructionsSection: React.FC<{ data: ReservationConfirmationData }> = ({ data }) => (
  <div className="space-y-4">
    <div className="bg-gray-100 p-4 rounded-md">
      <h3 className="font-medium text-gray-900 mb-3">Internal Coordinator Information</h3>
      <div className="space-y-2">
        {data.reservationId && <DetailRow label="Reservation ID" value={data.reservationId} />}
        {data.participants && <DetailRow label="Number of Participants" value={data.participants} />}
        {data.bridgeInstructions && <DetailRow label="Bridge Instructions" value={data.bridgeInstructions} />}
        {data.referenceName && <DetailRow label="Reference Name" value={data.referenceName} />}
        {data.notes && <DetailRow label="Notes" value={data.notes} />}
      </div>
    </div>
  </div>
);

// Helper Components
const DetailRow: React.FC<{ label: string; value: string }> = ({ label, value }) => (
  <div className="flex justify-between py-2 border-b border-gray-100">
    <span className="font-medium text-gray-600">{label}</span>
    <span className="text-gray-900 text-right">{value}</span>
  </div>
);

const SecureField: React.FC<{ label: string; value: string }> = ({ label, value }) => (
  <div className="flex justify-between py-2 border-b border-gray-100">
    <span className="font-medium text-gray-600">{label}</span>
    <span className="font-mono text-sm font-bold text-red-600 bg-red-50 px-2 py-1 rounded user-select-all">
      {value}
    </span>
  </div>
);

// Helper Functions
const hasAccessInfo = (data: ReservationConfirmationData): boolean => {
  return !!(data.hostPasscode || data.guestPasscode || data.conferenceId || 
           data.dialInNumbers || data.speakerDialInNumbers || data.participantDialInNumbers ||
           data.speakerDirectAccessLink || data.participantDirectAccessLink);
};

const hasAccessLinks = (data: ReservationConfirmationData): boolean => {
  return !!(data.speakerDirectAccessLink || data.participantDirectAccessLink || 
           data.multiviewAccessLink || data.replayAccessLink);
};

const hasImportantNotices = (data: ReservationConfirmationData): boolean => {
  return data.profileType === 'Assisted' || data.profileType === 'Passcode';
};

// Export function for generating HTML string directly
export const generateConfirmationHtml = (data: ReservationConfirmationData, customerOnly: boolean = true): string => {
  const sections = generateSections(data);
  const visibleSections = customerOnly ? sections.filter(s => s.customerVisible) : sections;
  
  // This would need to be implemented to convert React components to HTML strings
  // For now, return a placeholder
  return `<div>Confirmation HTML for ${data.companyName}</div>`;
};
