import { ReservationConfirmationData, ConfirmationSection } from '../components/ConfirmationRenderer';

export class ConfirmationHtmlGenerator {
  static generateEmailHtml(data: ReservationConfirmationData): string {
    const sections = this.generateSections(data);
    const customerVisibleSections = sections.filter(section => section.customerVisible);

    return `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Reservation Confirmation</title>
      </head>
      <body style="margin: 0; padding: 0; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; background-color: #f4f4f4;">
        <div style="max-width: 700px; margin: 20px auto; background: white; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); overflow: hidden;">
          
          <!-- Header -->
          <div style="background: linear-gradient(135deg, #1f2a44 0%, #2c3e50 100%); color: white; padding: 30px 20px; text-align: center;">
            <h1 style="margin: 0; font-size: 28px; font-weight: 300;">Reservation Confirmation</h1>
            <p style="margin: 10px 0 0 0; opacity: 0.9;">Your conference call has been scheduled</p>
          </div>

          <!-- Content -->
          <div style="padding: 30px;">
            ${customerVisibleSections.map(section => this.renderSectionForEmail(section, data)).join('')}
          </div>

          <!-- Footer -->
          <div style="background: #f8f9fa; padding: 20px; text-align: center; border-top: 1px solid #e1e8ed;">
            <p style="margin: 0; font-size: 12px; color: #666;">
              This message was generated by the Reservation Form system.<br>
              If you have any questions, please contact your conference coordinator.
            </p>
          </div>
          
        </div>
      </body>
      </html>
    `;
  }

  static generatePageHtml(data: ReservationConfirmationData): string {
    const sections = this.generateSections(data);

    return `
      <div class="space-y-8">
        ${sections.map(section => this.renderSectionForPage(section, data)).join('')}
      </div>
    `;
  }

  private static generateSections(data: ReservationConfirmationData): ConfirmationSection[] {
    const sections: ConfirmationSection[] = [];

    // Reservation Details Section (Customer Visible)
    sections.push({
      id: 'reservation-details',
      title: 'Reservation Details',
      customerVisible: true,
      content: null // We'll render directly in HTML
    });

    // Schedule Section (Customer Visible)
    if (data.callDate || data.startTime || data.timeZone) {
      sections.push({
        id: 'schedule',
        title: 'Call Schedule',
        customerVisible: true,
        content: null
      });
    }

    // Access Information Section (Customer Visible)
    if (this.hasAccessInfo(data)) {
      sections.push({
        id: 'access-information',
        title: 'Access / Dial-In Information',
        customerVisible: true,
        content: null
      });
    }

    // Access Links Section (Customer Visible)
    if (this.hasAccessLinks(data)) {
      sections.push({
        id: 'access-links',
        title: 'Access Links',
        customerVisible: true,
        content: null
      });
    }

    // Replay Information Section (Customer Visible)
    if (data.conferenceReplay === 'Yes' || data.multiview === 'Yes') {
      sections.push({
        id: 'replay-information',
        title: 'Replay Information',
        customerVisible: true,
        content: null
      });
    }

    // Important Notices Section (Customer Visible)
    if (this.hasImportantNotices(data)) {
      sections.push({
        id: 'important-notices',
        title: 'Important Notices / Instructions',
        customerVisible: true,
        content: null
      });
    }

    // Coordinator Instructions Section (Internal Only)
    sections.push({
      id: 'coordinator-instructions',
      title: 'Coordinator Instructions',
      customerVisible: false,
      content: null
    });

    return sections;
  }

  private static renderSectionForEmail(section: ConfirmationSection, data: ReservationConfirmationData): string {
    let content = '';

    switch (section.id) {
      case 'reservation-details':
        content = this.renderReservationDetailsForEmail(data);
        break;
      case 'schedule':
        content = this.renderScheduleForEmail(data);
        break;
      case 'access-information':
        content = this.renderAccessInformationForEmail(data);
        break;
      case 'access-links':
        content = this.renderAccessLinksForEmail(data);
        break;
      case 'replay-information':
        content = this.renderReplayInformationForEmail(data);
        break;
      case 'important-notices':
        content = this.renderImportantNoticesForEmail(data);
        break;
      case 'coordinator-instructions':
        content = this.renderCoordinatorInstructionsForEmail(data);
        break;
      default:
        content = '<div>Section content not available</div>';
    }

    return `
      <div style="margin-bottom: 30px;">
        <h2 style="color: #1f2a44; border-bottom: 2px solid #e1e8ed; padding-bottom: 10px; margin-bottom: 20px;">${section.title}</h2>
        ${content}
      </div>
    `;
  }

  private static renderSectionForPage(section: ConfirmationSection, data: ReservationConfirmationData): string {
    let content = '';

    switch (section.id) {
      case 'reservation-details':
        content = this.renderReservationDetailsForPage(data);
        break;
      case 'schedule':
        content = this.renderScheduleForPage(data);
        break;
      case 'access-information':
        content = this.renderAccessInformationForPage(data);
        break;
      case 'access-links':
        content = this.renderAccessLinksForPage(data);
        break;
      case 'replay-information':
        content = this.renderReplayInformationForPage(data);
        break;
      case 'important-notices':
        content = this.renderImportantNoticesForPage(data);
        break;
      case 'coordinator-instructions':
        content = this.renderCoordinatorInstructionsForPage(data);
        break;
      default:
        content = '<div>Section content not available</div>';
    }

    return `
      <div class="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden">
        <div class="px-6 py-4 bg-gray-50 border-b border-gray-200">
          <h2 class="text-lg font-semibold text-gray-900">${section.title}</h2>
        </div>
        <div class="p-6">
          ${content}
        </div>
      </div>
    `;
  }

  private static renderReservationDetailsForEmail(data: ReservationConfirmationData): string {
    return `
      <table cellpadding="12" cellspacing="0" style="border-collapse: collapse; width: 100%; font-size: 14px;">
        <tr>
          <td style="font-weight: 600; color: #555; width: 180px; vertical-align: top;">Profile Type</td>
          <td style="background: #f8f9fa; padding: 12px; border-radius: 4px;">${data.profileType}</td>
        </tr>
        <tr>
          <td style="font-weight: 600; color: #555; width: 180px; vertical-align: top;">Call Type</td>
          <td style="background: #f8f9fa; padding: 12px; border-radius: 4px;">${data.callType}</td>
        </tr>
        <tr>
          <td style="font-weight: 600; color: #555; width: 180px; vertical-align: top;">Company Name</td>
          <td style="background: #f8f9fa; padding: 12px; border-radius: 4px;">${data.companyName}</td>
        </tr>
        ${data.dealName ? `
        <tr>
          <td style="font-weight: 600; color: #555; width: 180px; vertical-align: top;">Deal / Reference Name</td>
          <td style="background: #f8f9fa; padding: 12px; border-radius: 4px;">${data.dealName}</td>
        </tr>` : ''}
        ${data.setupName ? `
        <tr>
          <td style="font-weight: 600; color: #555; width: 180px; vertical-align: top;">Setup Contact</td>
          <td style="background: #f8f9fa; padding: 12px; border-radius: 4px;">${data.setupName}</td>
        </tr>` : ''}
        ${data.setupEmail ? `
        <tr>
          <td style="font-weight: 600; color: #555; width: 180px; vertical-align: top;">Setup Email</td>
          <td style="background: #f8f9fa; padding: 12px; border-radius: 4px;">${data.setupEmail}</td>
        </tr>` : ''}
      </table>
    `;
  }

  private static renderReservationDetailsForPage(data: ReservationConfirmationData): string {
    return `
      <div class="space-y-4">
        <div class="flex justify-between py-2 border-b border-gray-100">
          <span class="font-medium text-gray-600">Profile Type</span>
          <span class="text-gray-900 text-right">${data.profileType}</span>
        </div>
        <div class="flex justify-between py-2 border-b border-gray-100">
          <span class="font-medium text-gray-600">Call Type</span>
          <span class="text-gray-900 text-right">${data.callType}</span>
        </div>
        <div class="flex justify-between py-2 border-b border-gray-100">
          <span class="font-medium text-gray-600">Company Name</span>
          <span class="text-gray-900 text-right">${data.companyName}</span>
        </div>
        ${data.dealName ? `
        <div class="flex justify-between py-2 border-b border-gray-100">
          <span class="font-medium text-gray-600">Deal / Reference Name</span>
          <span class="text-gray-900 text-right">${data.dealName}</span>
        </div>` : ''}
        ${data.setupName ? `
        <div class="flex justify-between py-2 border-b border-gray-100">
          <span class="font-medium text-gray-600">Setup Contact</span>
          <span class="text-gray-900 text-right">${data.setupName}</span>
        </div>` : ''}
        ${data.setupEmail ? `
        <div class="flex justify-between py-2 border-b border-gray-100">
          <span class="font-medium text-gray-600">Setup Email</span>
          <span class="text-gray-900 text-right">${data.setupEmail}</span>
        </div>` : ''}
      </div>
    `;
  }

  private static renderScheduleForEmail(data: ReservationConfirmationData): string {
    return `
      <table cellpadding="12" cellspacing="0" style="border-collapse: collapse; width: 100%; font-size: 14px;">
        ${data.callDate ? `
        <tr>
          <td style="font-weight: 600; color: #555; width: 180px; vertical-align: top;">Date</td>
          <td style="background: #f8f9fa; padding: 12px; border-radius: 4px;">${data.callDate}</td>
        </tr>` : ''}
        ${data.startTime ? `
        <tr>
          <td style="font-weight: 600; color: #555; width: 180px; vertical-align: top;">Time</td>
          <td style="background: #f8f9fa; padding: 12px; border-radius: 4px;">${data.startTime}${data.timeZone ? ` (${data.timeZone})` : ""}</td>
        </tr>` : ''}
        ${data.duration ? `
        <tr>
          <td style="font-weight: 600; color: #555; width: 180px; vertical-align: top;">Duration</td>
          <td style="background: #f8f9fa; padding: 12px; border-radius: 4px;">${data.duration}</td>
        </tr>` : ''}
        ${data.host ? `
        <tr>
          <td style="font-weight: 600; color: #555; width: 180px; vertical-align: top;">Host</td>
          <td style="background: #f8f9fa; padding: 12px; border-radius: 4px;">${data.host}</td>
        </tr>` : ''}
      </table>
    `;
  }

  private static renderScheduleForPage(data: ReservationConfirmationData): string {
    return `
      <div class="space-y-4">
        ${data.callDate ? `
        <div class="flex justify-between py-2 border-b border-gray-100">
          <span class="font-medium text-gray-600">Date</span>
          <span class="text-gray-900 text-right">${data.callDate}</span>
        </div>` : ''}
        ${data.startTime ? `
        <div class="flex justify-between py-2 border-b border-gray-100">
          <span class="font-medium text-gray-600">Time</span>
          <span class="text-gray-900 text-right">${data.startTime}${data.timeZone ? ` (${data.timeZone})` : ""}</span>
        </div>` : ''}
        ${data.duration ? `
        <div class="flex justify-between py-2 border-b border-gray-100">
          <span class="font-medium text-gray-600">Duration</span>
          <span class="text-gray-900 text-right">${data.duration}</span>
        </div>` : ''}
        ${data.host ? `
        <div class="flex justify-between py-2 border-b border-gray-100">
          <span class="font-medium text-gray-600">Host</span>
          <span class="text-gray-900 text-right">${data.host}</span>
        </div>` : ''}
      </div>
    `;
  }

  private static renderAccessInformationForEmail(data: ReservationConfirmationData): string {
    return `
      ${data.dialInNumbers ? `
      <div style="margin-bottom: 20px;">
        <h3 style="color: #2c3e50; margin: 0 0 10px 0; font-size: 16px;">Dial-In Numbers</h3>
        <div style="background: #e8f4fd; border-left: 4px solid #2196f3; padding: 15px; border-radius: 4px; user-select: all;">
          ${data.dialInNumbers.replace(/\n/g, '<br>')}
        </div>
      </div>` : ''}
      
      ${data.internationalDialInNumbers ? `
      <div style="margin-bottom: 20px;">
        <h3 style="color: #2c3e50; margin: 0 0 10px 0; font-size: 16px;">International Dial-In Numbers</h3>
        <div style="background: #e8f4fd; border-left: 4px solid #2196f3; padding: 15px; border-radius: 4px; user-select: all;">
          ${data.internationalDialInNumbers.replace(/\n/g, '<br>')}
        </div>
      </div>` : ''}
      
      ${data.speakerDialInNumbers ? `
      <div style="margin-bottom: 20px;">
        <h3 style="color: #2c3e50; margin: 0 0 10px 0; font-size: 16px;">Speaker Dial-In Numbers</h3>
        <div style="background: #fff3cd; border-left: 4px solid #ffc107; padding: 15px; border-radius: 4px; user-select: all;">
          ${data.speakerDialInNumbers.replace(/\n/g, '<br>')}
        </div>
      </div>` : ''}
      
      ${data.participantDialInNumbers ? `
      <div style="margin-bottom: 20px;">
        <h3 style="color: #2c3e50; margin: 0 0 10px 0; font-size: 16px;">Participant Dial-In Numbers</h3>
        <div style="background: #fff3cd; border-left: 4px solid #ffc107; padding: 15px; border-radius: 4px; user-select: all;">
          ${data.participantDialInNumbers.replace(/\n/g, '<br>')}
        </div>
      </div>` : ''}
      
      <table cellpadding="12" cellspacing="0" style="border-collapse: collapse; width: 100%; font-size: 14px;">
        ${data.hostPasscode ? `
        <tr>
          <td style="font-weight: 600; color: #555; width: 180px; vertical-align: top;">Host Passcode</td>
          <td style="background: #ffebee; border-left: 4px solid #f44336; padding: 12px; border-radius: 4px; font-family: monospace; font-size: 16px; font-weight: bold; user-select: all;">${data.hostPasscode}</td>
        </tr>` : ''}
        ${data.guestPasscode ? `
        <tr>
          <td style="font-weight: 600; color: #555; width: 180px; vertical-align: top;">Guest Passcode</td>
          <td style="background: #ffebee; border-left: 4px solid #f44336; padding: 12px; border-radius: 4px; font-family: monospace; font-size: 16px; font-weight: bold; user-select: all;">${data.guestPasscode}</td>
        </tr>` : ''}
        ${data.conferenceId ? `
        <tr>
          <td style="font-weight: 600; color: #555; width: 180px; vertical-align: top;">Conference ID</td>
          <td style="background: #e8f5e8; border-left: 4px solid #4caf50; padding: 12px; border-radius: 4px; font-family: monospace; font-size: 16px; font-weight: bold; user-select: all;">${data.conferenceId}</td>
        </tr>` : ''}
        ${data.reservationId ? `
        <tr>
          <td style="font-weight: 600; color: #555; width: 180px; vertical-align: top;">Reservation ID</td>
          <td style="background: #f8f9fa; padding: 12px; border-radius: 4px;">${data.reservationId}</td>
        </tr>` : ''}
      </table>
    `;
  }

  private static renderAccessInformationForPage(data: ReservationConfirmationData): string {
    return `
      <div class="space-y-4">
        ${data.dialInNumbers ? `
        <div>
          <h3 class="font-medium text-gray-900 mb-2">Dial-In Numbers</h3>
          <div class="bg-blue-50 border-l-4 border-blue-400 p-3 rounded user-select-all">
            <pre class="text-sm whitespace-pre-wrap">${data.dialInNumbers}</pre>
          </div>
        </div>` : ''}
        
        ${data.internationalDialInNumbers ? `
        <div>
          <h3 class="font-medium text-gray-900 mb-2">International Dial-In Numbers</h3>
          <div class="bg-blue-50 border-l-4 border-blue-400 p-3 rounded user-select-all">
            <pre class="text-sm whitespace-pre-wrap">${data.internationalDialInNumbers}</pre>
          </div>
        </div>` : ''}
        
        ${data.speakerDialInNumbers ? `
        <div>
          <h3 class="font-medium text-gray-900 mb-2">Speaker Dial-In Numbers</h3>
          <div class="bg-yellow-50 border-l-4 border-yellow-400 p-3 rounded user-select-all">
            <pre class="text-sm whitespace-pre-wrap">${data.speakerDialInNumbers}</pre>
          </div>
        </div>` : ''}
        
        ${data.participantDialInNumbers ? `
        <div>
          <h3 class="font-medium text-gray-900 mb-2">Participant Dial-In Numbers</h3>
          <div class="bg-yellow-50 border-l-4 border-yellow-400 p-3 rounded user-select-all">
            <pre class="text-sm whitespace-pre-wrap">${data.participantDialInNumbers}</pre>
          </div>
        </div>` : ''}
        
        <div class="space-y-3">
          ${data.hostPasscode ? `
          <div class="flex justify-between py-2 border-b border-gray-100">
            <span class="font-medium text-gray-600">Host Passcode</span>
            <span class="font-mono text-sm font-bold text-red-600 bg-red-50 px-2 py-1 rounded user-select-all">${data.hostPasscode}</span>
          </div>` : ''}
          ${data.guestPasscode ? `
          <div class="flex justify-between py-2 border-b border-gray-100">
            <span class="font-medium text-gray-600">Guest Passcode</span>
            <span class="font-mono text-sm font-bold text-red-600 bg-red-50 px-2 py-1 rounded user-select-all">${data.guestPasscode}</span>
          </div>` : ''}
          ${data.conferenceId ? `
          <div class="flex justify-between py-2 border-b border-gray-100">
            <span class="font-medium text-gray-600">Conference ID</span>
            <span class="font-mono text-sm font-bold text-green-600 bg-green-50 px-2 py-1 rounded user-select-all">${data.conferenceId}</span>
          </div>` : ''}
          ${data.reservationId ? `
          <div class="flex justify-between py-2 border-b border-gray-100">
            <span class="font-medium text-gray-600">Reservation ID</span>
            <span class="text-gray-900 text-right">${data.reservationId}</span>
          </div>` : ''}
        </div>
      </div>
    `;
  }

  private static renderAccessLinksForEmail(data: ReservationConfirmationData): string {
    return `
      ${data.speakerDirectAccessLink ? `
      <div style="margin-bottom: 20px;">
        <h3 style="color: #2c3e50; margin: 0 0 10px 0; font-size: 16px;">Speaker Direct Access Link</h3>
        <div style="background: #f3e5f5; border-left: 4px solid #9c27b0; padding: 15px; border-radius: 4px;">
          <a href="${data.speakerDirectAccessLink}" style="color: #9c27b0; text-decoration: none; font-weight: 600; user-select: all;">${data.speakerDirectAccessLink}</a>
        </div>
      </div>` : ''}
      
      ${data.participantDirectAccessLink ? `
      <div style="margin-bottom: 20px;">
        <h3 style="color: #2c3e50; margin: 0 0 10px 0; font-size: 16px;">Participant Direct Access Link</h3>
        <div style="background: #f3e5f5; border-left: 4px solid #9c27b0; padding: 15px; border-radius: 4px;">
          <a href="${data.participantDirectAccessLink}" style="color: #9c27b0; text-decoration: none; font-weight: 600; user-select: all;">${data.participantDirectAccessLink}</a>
        </div>
      </div>` : ''}
      
      ${data.multiview === 'Yes' && data.multiviewAccessLink ? `
      <div style="margin-bottom: 20px;">
        <h3 style="color: #2c3e50; margin: 0 0 10px 0; font-size: 16px;">Multiview Access Link</h3>
        <div style="background: #e3f2fd; border-left: 4px solid #1976d2; padding: 15px; border-radius: 4px;">
          <a href="${data.multiviewAccessLink}" style="color: #1976d2; text-decoration: none; font-weight: 600; user-select: all;">${data.multiviewAccessLink}</a>
        </div>
      </div>` : ''}
      
      ${data.conferenceReplay === 'Yes' && data.replayAccessLink ? `
      <div style="margin-bottom: 20px;">
        <h3 style="color: #2c3e50; margin: 0 0 10px 0; font-size: 16px;">Conference Replay Link</h3>
        <div style="background: #e8f5e8; border-left: 4px solid #4caf50; padding: 15px; border-radius: 4px;">
          <a href="${data.replayAccessLink}" style="color: #4caf50; text-decoration: none; font-weight: 600; user-select: all;">${data.replayAccessLink}</a>
        </div>
      </div>` : ''}
    `;
  }

  private static renderAccessLinksForPage(data: ReservationConfirmationData): string {
    return `
      <div class="space-y-4">
        ${data.speakerDirectAccessLink ? `
        <div>
          <h3 class="font-medium text-gray-900 mb-2">Speaker Direct Access Link</h3>
          <div class="bg-purple-50 border-l-4 border-purple-400 p-3 rounded">
            <a href="${data.speakerDirectAccessLink}" class="text-purple-700 hover:text-purple-900 underline break-all user-select-all" target="_blank" rel="noopener noreferrer">
              ${data.speakerDirectAccessLink}
            </a>
          </div>
        </div>` : ''}
        
        ${data.participantDirectAccessLink ? `
        <div>
          <h3 class="font-medium text-gray-900 mb-2">Participant Direct Access Link</h3>
          <div class="bg-purple-50 border-l-4 border-purple-400 p-3 rounded">
            <a href="${data.participantDirectAccessLink}" class="text-purple-700 hover:text-purple-900 underline break-all user-select-all" target="_blank" rel="noopener noreferrer">
              ${data.participantDirectAccessLink}
            </a>
          </div>
        </div>` : ''}
        
        ${data.multiview === 'Yes' && data.multiviewAccessLink ? `
        <div>
          <h3 class="font-medium text-gray-900 mb-2">Multiview Access Link</h3>
          <div class="bg-blue-50 border-l-4 border-blue-400 p-3 rounded">
            <a href="${data.multiviewAccessLink}" class="text-blue-700 hover:text-blue-900 underline break-all user-select-all" target="_blank" rel="noopener noreferrer">
              ${data.multiviewAccessLink}
            </a>
          </div>
        </div>` : ''}
        
        ${data.conferenceReplay === 'Yes' && data.replayAccessLink ? `
        <div>
          <h3 class="font-medium text-gray-900 mb-2">Conference Replay Link</h3>
          <div class="bg-green-50 border-l-4 border-green-400 p-3 rounded">
            <a href="${data.replayAccessLink}" class="text-green-700 hover:text-green-900 underline break-all user-select-all" target="_blank" rel="noopener noreferrer">
              ${data.replayAccessLink}
            </a>
          </div>
        </div>` : ''}
      </div>
    `;
  }

  private static renderReplayInformationForEmail(data: ReservationConfirmationData): string {
    return `
      ${data.conferenceReplay === 'Yes' ? `
      <div style="margin-bottom: 20px;">
        <h3 style="color: #2c3e50; margin: 0 0 10px 0; font-size: 16px;">Conference Replay</h3>
        <div style="background: #f8f9fa; padding: 15px; border-radius: 4px;">
          <table cellpadding="8" cellspacing="0" style="border-collapse: collapse; width: 100%; font-size: 14px;">
            ${data.replayFromDate ? `
            <tr>
              <td style="font-weight: 600; color: #555; width: 120px;">From Date</td>
              <td>${data.replayFromDate}</td>
            </tr>` : ''}
            ${data.replayToDate ? `
            <tr>
              <td style="font-weight: 600; color: #555; width: 120px;">To Date</td>
              <td>${data.replayToDate}</td>
            </tr>` : ''}
            ${data.replayEndTime ? `
            <tr>
              <td style="font-weight: 600; color: #555; width: 120px;">End Time</td>
              <td>${data.replayEndTime}</td>
            </tr>` : ''}
            ${data.replayTimeZone ? `
            <tr>
              <td style="font-weight: 600; color: #555; width: 120px;">Time Zone</td>
              <td>${data.replayTimeZone}</td>
            </tr>` : ''}
            ${data.replayCode ? `
            <tr>
              <td style="font-weight: 600; color: #555; width: 120px;">Replay Code</td>
              <td style="background: #e8f5e8; border-left: 4px solid #4caf50; padding: 8px; border-radius: 4px; font-family: monospace; font-size: 14px; font-weight: bold; user-select: all;">${data.replayCode}</td>
            </tr>` : ''}
          </table>
        </div>
      </div>` : ''}
      
      ${data.multiview === 'Yes' ? `
      <div style="margin-bottom: 20px;">
        <h3 style="color: #2c3e50; margin: 0 0 10px 0; font-size: 16px;">Multiview Details</h3>
        <div style="background: #f8f9fa; padding: 15px; border-radius: 4px;">
          <table cellpadding="8" cellspacing="0" style="border-collapse: collapse; width: 100%; font-size: 14px;">
            ${data.multiviewUsername ? `
            <tr>
              <td style="font-weight: 600; color: #555; width: 120px;">Username</td>
              <td>${data.multiviewUsername}</td>
            </tr>` : ''}
            ${data.multiviewConferenceNumber ? `
            <tr>
              <td style="font-weight: 600; color: #555; width: 120px;">Conference Number</td>
              <td>${data.multiviewConferenceNumber}</td>
            </tr>` : ''}
          </table>
        </div>
      </div>` : ''}
    `;
  }

  private static renderReplayInformationForPage(data: ReservationConfirmationData): string {
    return `
      <div class="space-y-4">
        ${data.conferenceReplay === 'Yes' ? `
        <div>
          <h3 class="font-medium text-gray-900 mb-2">Conference Replay</h3>
          <div class="bg-gray-50 p-3 rounded space-y-2">
            ${data.replayFromDate ? `
            <div class="flex justify-between py-2 border-b border-gray-100">
              <span class="font-medium text-gray-600">From Date</span>
              <span class="text-gray-900 text-right">${data.replayFromDate}</span>
            </div>` : ''}
            ${data.replayToDate ? `
            <div class="flex justify-between py-2 border-b border-gray-100">
              <span class="font-medium text-gray-600">To Date</span>
              <span class="text-gray-900 text-right">${data.replayToDate}</span>
            </div>` : ''}
            ${data.replayEndTime ? `
            <div class="flex justify-between py-2 border-b border-gray-100">
              <span class="font-medium text-gray-600">End Time</span>
              <span class="text-gray-900 text-right">${data.replayEndTime}</span>
            </div>` : ''}
            ${data.replayTimeZone ? `
            <div class="flex justify-between py-2 border-b border-gray-100">
              <span class="font-medium text-gray-600">Time Zone</span>
              <span class="text-gray-900 text-right">${data.replayTimeZone}</span>
            </div>` : ''}
            ${data.replayCode ? `
            <div class="flex justify-between py-2 border-b border-gray-100">
              <span class="font-medium text-gray-600">Replay Code</span>
              <span class="font-mono text-sm font-bold text-green-600 bg-green-50 px-2 py-1 rounded user-select-all">${data.replayCode}</span>
            </div>` : ''}
          </div>
        </div>` : ''}
        
        ${data.multiview === 'Yes' ? `
        <div>
          <h3 class="font-medium text-gray-900 mb-2">Multiview Details</h3>
          <div class="bg-gray-50 p-3 rounded space-y-2">
            ${data.multiviewUsername ? `
            <div class="flex justify-between py-2 border-b border-gray-100">
              <span class="font-medium text-gray-600">Username</span>
              <span class="text-gray-900 text-right">${data.multiviewUsername}</span>
            </div>` : ''}
            ${data.multiviewConferenceNumber ? `
            <div class="flex justify-between py-2 border-b border-gray-100">
              <span class="font-medium text-gray-600">Conference Number</span>
              <span class="text-gray-900 text-right">${data.multiviewConferenceNumber}</span>
            </div>` : ''}
          </div>
        </div>` : ''}
      </div>
    `;
  }

  private static renderImportantNoticesForEmail(data: ReservationConfirmationData): string {
    return `
      ${data.profileType === 'Assisted' ? `
      <div style="background-color: #fff3cd; border: 1px solid #ffeaa7; padding: 15px; margin: 20px 0; border-radius: 5px;">
        <p style="margin: 0; color: #856404; font-weight: bold;">Please note that we have provided the following Direct Access links to your Invite:</p>
        <ul style="margin: 10px 0; color: #856404;">
          <li>Speaker Direct Access Link</li>
          <li>Participant Direct Access Link</li>
        </ul>
        <p style="margin: 0; color: #856404;">It is imperative that the correct Direct Access link is provided to the correct intended party to avoid Participants joining the Speaker Sub Conference prior to call start time.</p>
      </div>` : ''}
      
      ${(data.profileType === 'Assisted' || data.profileType === 'Passcode') ? `
      <div style="background-color: #f8d7da; border: 1px solid #f5c6cb; padding: 15px; margin: 20px 0; border-radius: 5px;">
        <p style="margin: 0; color: #721c24; font-weight: bold;">
          Please provide the SPEAKER DIAL IN NUMBERS and SPEAKER Conference ID to the Technician if the call is taking place in an Auditorium and a Main Feed Line is needed to connect the call from the Auditorium to our Conferencing Bridge
        </p>
      </div>` : ''}
    `;
  }

  private static renderImportantNoticesForPage(data: ReservationConfirmationData): string {
    return `
      <div class="space-y-4">
        ${data.profileType === 'Assisted' ? `
        <div class="bg-yellow-50 border border-yellow-200 p-4 rounded-md">
          <p class="text-sm text-yellow-800 font-medium mb-2">
            Please note that we have provided the following Direct Access links to your Invite:
          </p>
          <ul class="text-sm text-yellow-800 space-y-1 ml-4">
            <li>• Speaker Direct Access Link</li>
            <li>• Participant Direct Access Link</li>
          </ul>
          <p class="text-sm text-yellow-800 mt-2">
            It is imperative that the correct Direct Access link is provided to the correct intended party to avoid Participants joining the Speaker Sub Conference prior to call start time.
          </p>
        </div>` : ''}
        
        ${(data.profileType === 'Assisted' || data.profileType === 'Passcode') ? `
        <div class="bg-red-50 border border-red-200 p-4 rounded-md">
          <p class="text-sm text-red-800 font-bold">
            Please provide the SPEAKER DIAL IN NUMBERS and SPEAKER Conference ID to the Technician if the call is taking place in an Auditorium and a Main Feed Line is needed to connect the call from the Auditorium to our Conferencing Bridge
          </p>
        </div>` : ''}
      </div>
    `;
  }

  private static renderCoordinatorInstructionsForEmail(data: ReservationConfirmationData): string {
    return `
      <div style="background: #f8f9fa; padding: 15px; border-radius: 4px; border-left: 4px solid #6c757d;">
        <h3 style="color: #495057; margin: 0 0 10px 0; font-size: 16px;">Internal Coordinator Information</h3>
        <table cellpadding="8" cellspacing="0" style="border-collapse: collapse; width: 100%; font-size: 14px;">
          ${data.reservationId ? `
          <tr>
            <td style="font-weight: 600; color: #555; width: 140px;">Reservation ID</td>
            <td>${data.reservationId}</td>
          </tr>` : ''}
          ${data.participants ? `
          <tr>
            <td style="font-weight: 600; color: #555; width: 140px;">Number of Participants</td>
            <td>${data.participants}</td>
          </tr>` : ''}
          ${data.bridgeInstructions ? `
          <tr>
            <td style="font-weight: 600; color: #555; width: 140px;">Bridge Instructions</td>
            <td>${data.bridgeInstructions}</td>
          </tr>` : ''}
          ${data.referenceName ? `
          <tr>
            <td style="font-weight: 600; color: #555; width: 140px;">Reference Name</td>
            <td>${data.referenceName}</td>
          </tr>` : ''}
          ${data.notes ? `
          <tr>
            <td style="font-weight: 600; color: #555; width: 140px;">Notes</td>
            <td>${data.notes}</td>
          </tr>` : ''}
        </table>
      </div>
    `;
  }

  private static renderCoordinatorInstructionsForPage(data: ReservationConfirmationData): string {
    return `
      <div class="space-y-4">
        <div class="bg-gray-100 p-4 rounded-md">
          <h3 class="font-medium text-gray-900 mb-3">Internal Coordinator Information</h3>
          <div class="space-y-2">
            ${data.reservationId ? `
            <div class="flex justify-between py-2 border-b border-gray-100">
              <span class="font-medium text-gray-600">Reservation ID</span>
              <span class="text-gray-900 text-right">${data.reservationId}</span>
            </div>` : ''}
            ${data.participants ? `
            <div class="flex justify-between py-2 border-b border-gray-100">
              <span class="font-medium text-gray-600">Number of Participants</span>
              <span class="text-gray-900 text-right">${data.participants}</span>
            </div>` : ''}
            ${data.bridgeInstructions ? `
            <div class="flex justify-between py-2 border-b border-gray-100">
              <span class="font-medium text-gray-600">Bridge Instructions</span>
              <span class="text-gray-900 text-right">${data.bridgeInstructions}</span>
            </div>` : ''}
            ${data.referenceName ? `
            <div class="flex justify-between py-2 border-b border-gray-100">
              <span class="font-medium text-gray-600">Reference Name</span>
              <span class="text-gray-900 text-right">${data.referenceName}</span>
            </div>` : ''}
            ${data.notes ? `
            <div class="flex justify-between py-2 border-b border-gray-100">
              <span class="font-medium text-gray-600">Notes</span>
              <span class="text-gray-900 text-right">${data.notes}</span>
            </div>` : ''}
          </div>
        </div>
      </div>
    `;
  }

  // Helper functions
  private static hasAccessInfo(data: ReservationConfirmationData): boolean {
    return !!(data.hostPasscode || data.guestPasscode || data.conferenceId || 
             data.dialInNumbers || data.speakerDialInNumbers || data.participantDialInNumbers ||
             data.internationalDialInNumbers || data.speakerInternationalDialInNumbers || 
             data.participantInternationalDialInNumbers);
  }

  private static hasAccessLinks(data: ReservationConfirmationData): boolean {
    return !!(data.speakerDirectAccessLink || data.participantDirectAccessLink || 
             data.multiviewAccessLink || data.replayAccessLink);
  }

  private static hasImportantNotices(data: ReservationConfirmationData): boolean {
    return data.profileType === 'Assisted' || data.profileType === 'Passcode';
  }
}
