// lib/formatEmail.ts

export type ReservationEmailData = {
  profileType: string;
  callType: string;
  companyName: string;

  dealName?: string;
  setupName?: string;
  setupEmail?: string;

  callDate?: string;
  startTime?: string;
  timeZone?: string;

  hostPasscode?: string;
  guestPasscode?: string;

  conferenceId?: string;
  notes?: string;
};

/**
 * Builds an HTML email body for a reservation.
 */
export function formatHtmlEmail(res: ReservationEmailData): string {
  return `
    <div style="font-family: Arial, sans-serif; line-height: 1.5;">
      <h2 style="color:#1f2a44;">Reservation Details</h2>

      <table cellpadding="6" cellspacing="0" style="border-collapse: collapse; width: 100%; max-width: 600px;">
        <tr>
          <td style="font-weight:bold; border-bottom:1px solid #eee; width: 200px;">Profile Type</td>
          <td style="border-bottom:1px solid #eee;">${res.profileType}</td>
        </tr>
        <tr>
          <td style="font-weight:bold; border-bottom:1px solid #eee;">Call Type</td>
          <td style="border-bottom:1px solid #eee;">${res.callType}</td>
        </tr>
        <tr>
          <td style="font-weight:bold; border-bottom:1px solid #eee;">Company Name</td>
          <td style="border-bottom:1px solid #eee;">${res.companyName}</td>
        </tr>
        ${
          res.dealName
            ? `
        <tr>
          <td style="font-weight:bold; border-bottom:1px solid #eee;">Deal / Reference Name</td>
          <td style="border-bottom:1px solid #eee;">${res.dealName}</td>
        </tr>`
            : ""
        }
        ${
          res.setupName
            ? `
        <tr>
          <td style="font-weight:bold; border-bottom:1px solid #eee;">Setup Contact</td>
          <td style="border-bottom:1px solid #eee;">${res.setupName}</td>
        </tr>`
            : ""
        }
        ${
          res.setupEmail
            ? `
        <tr>
          <td style="font-weight:bold; border-bottom:1px solid #eee;">Setup Email</td>
          <td style="border-bottom:1px solid #eee;">${res.setupEmail}</td>
        </tr>`
            : ""
        }
        ${
          res.callDate || res.startTime || res.timeZone
            ? `
        <tr>
          <td style="font-weight:bold; border-bottom:1px solid #eee;">Date / Time</td>
          <td style="border-bottom:1px solid #eee;">
            ${res.callDate ?? ""} ${res.startTime ?? ""}${
                res.timeZone ? ` (${res.timeZone})` : ""
              }
          </td>
        </tr>`
            : ""
        }
        ${
          res.hostPasscode
            ? `
        <tr>
          <td style="font-weight:bold; border-bottom:1px solid #eee;">Host Passcode</td>
          <td style="border-bottom:1px solid #eee;">${res.hostPasscode}</td>
        </tr>`
            : ""
        }
        ${
          res.guestPasscode
            ? `
        <tr>
          <td style="font-weight:bold; border-bottom:1px solid #eee;">Guest Passcode</td>
          <td style="border-bottom:1px solid #eee;">${res.guestPasscode}</td>
        </tr>`
            : ""
        }
        ${
          res.conferenceId
            ? `
        <tr>
          <td style="font-weight:bold; border-bottom:1px solid #eee;">Conference ID</td>
          <td style="border-bottom:1px solid #eee;">${res.conferenceId}</td>
        </tr>`
            : ""
        }
        ${
          res.notes
            ? `
        <tr>
          <td style="font-weight:bold; vertical-align:top;">Notes</td>
          <td>${res.notes}</td>
        </tr>`
            : ""
        }
      </table>

      <p style="margin-top:16px; font-size: 12px; color:#666;">
        This message was generated by the Reservation Form system.
      </p>
    </div>
  `;
}
